In [4]:
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.ticker as ticker
import matplotlib.animation as animation
import emoji
from IPython.display import HTML
import warnings
warnings.filterwarnings('ignore')
!pip install colour

Collecting colour
  Downloading https://files.pythonhosted.org/packages/74/46/e81907704ab203206769dee1385dc77e1407576ff8f50a0681d0a6b541be/colour-0.1.5-py2.py3-none-any.whl
Installing collected packages: colour
Successfully installed colour-0.1.5

In [7]:
from google.colab import files
df = files.upload()

Saving datasets_494724_1196190_time_series_covid_19_confirmed.csv to datasets_494724_1196190_time_series_covid_19_confirmed.csv

In [0]:
df = pd.read_csv(io.BytesIO(df['datasets_494724_1196190_time_series_covid_19_confirmed.csv']))

In [14]:
df

    Province/State         Country/Region  ...  05/27/2020  05/28/2020
0              NaN            Afghanistan  ...       12456       13036
1              NaN                Albania  ...        1050        1076
2              NaN                Algeria  ...        8857        8997
3              NaN                Andorra  ...         763         763
4              NaN                 Angola  ...          71          74
..             ...                    ...  ...         ...         ...
261            NaN  Sao Tome and Principe  ...         443         458
262            NaN                  Yemen  ...         256         278
263            NaN                Comoros  ...          87          87
264            NaN             Tajikistan  ...        3424        3563
265            NaN                Lesotho  ...           2           2

[266 rows x 132 columns]

In [0]:
dates = df.columns[4:]

In [20]:
dates

Index(['01/22/2020', '01/23/2020', '01/24/2020', '01/25/2020', '01/26/2020',
       '01/27/2020', '01/28/2020', '01/29/2020', '01/30/2020', '01/31/2020',
       ...
       '05/19/2020', '05/20/2020', '05/21/2020', '05/22/2020', '05/23/2020',
       '05/24/2020', '05/25/2020', '05/26/2020', '05/27/2020', '05/28/2020'],
      dtype='object', length=128)

In [0]:
confirmed = df.melt(id_vars=['Province/State', 'Country/Region', 'Lat', 'Long'], 
                            value_vars=dates, var_name='Date', value_name='Confirmed')

In [0]:
adj_dates = confirmed .Date.unique()

In [0]:
def genratepseudorandomcolors():
    import random
    from colour import Color
    random_i = random.randint(0,10000000)
    random_j = random.randint(0,10000000)
    c = Color(random_i,random_j)
    hex_number = c.hex_l
    return hex_number

In [0]:
colours = []
for i in range(len(confirmed['Country/Region'].unique())) :
    colours.append(genratepseudorandomcolors())

In [0]:
colorsset = dict(zip(
    [i for i in df['Country/Region'].unique()],
    colours
))

In [0]:
start_date ='1/22/20'
current_date = start_date

In [0]:
def draw_barchart_conf(current_date):
    
    #creating dataframe for plotting 
    #In each loop it contains top 10 coutires having most number of confirmed cases
    dff = confirmed[confirmed['Date'].eq(current_date)].groupby('Country/Region').sum().sort_values(by='Confirmed', ascending=False).head(10)
    dff = dff.reset_index()
    dff = dff[::-1]
    ax.clear()
    ax.barh(dff['Country/Region'], dff['Confirmed'], color=[colorsset[x] for x in dff['Country/Region']])
    dx = dff['Confirmed'].max() / 200
    for i, (value, name) in enumerate(zip(dff['Confirmed'], dff['Country/Region'])):
        
        ax.text(value-dx, i,     name,           size=14, weight=600, ha='right', va='bottom')
        ax.text(value+dx, i,     f'{value:,.0f}',  size=14, ha='left',  va='center')
    
    
    ax.text(1, 0.4, current_date, transform=ax.transAxes, color='#777777', size=46, ha='right', weight=800)
    ax.text(0, 1.06, 'Population', transform=ax.transAxes, size=12, color='#777777')
    ax.xaxis.set_major_formatter(ticker.StrMethodFormatter('{x:,.0f}'))
    ax.xaxis.set_ticks_position('top')
    ax.tick_params(axis='x', colors='#777777', labelsize=12)
    ax.set_yticks([])
    ax.margins(0, 0.01)
    ax.grid(which='major', axis='x', linestyle='-')
    ax.set_axisbelow(True)
    
    #adding other textual infomations
    ax.text(0, 1.15, f'CORONA confirmed cases in the world',
            transform=ax.transAxes, size=24, weight=600, ha='left', va='top')
    ax.text(1, 0, 'by @Thiru', transform=ax.transAxes, color='#777777', ha='right',
          bbox=dict(facecolor='white', alpha=0.8, edgecolor='white'))
    #plt.box(False)
    
#draw_barchart_conf(current_date=start_date)

In [0]:
#fig, ax = plt.subplots(figsize=(15, 8))
#animator = animation.FuncAnimation(fig, draw_barchart_conf, frames=adj_dates)
#HTML(animator.to_html5_video())

In [88]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [93]:
sav = HTML(animator.to_html5_video())

files.download("sav")

FileNotFoundError: ignored